// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package protos;

public final class ChatOuterClass {
  private ChatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ReceiveMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ReceiveMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\006protos\"0\n\014LoginRequest\022\016\n\006" +
      "userId\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"1\n\rLoginR" +
      "esponse\022\016\n\006status\030\001 \001(\t\022\020\n\010jwtToken\030\002 \001(" +
      "\t\"P\n\022SendMessageRequest\022\027\n\017recipientUser" +
      "Id\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\020\n\010jwtToken\030\003 " +
      "\001(\t\"%\n\023SendMessageResponse\022\016\n\006status\030\001 \001" +
      "(\t\")\n\025ReceiveMessageRequest\022\020\n\010jwtToken\030" +
      "\001 \001(\t\"(\n\007Message\022\014\n\004from\030\001 \001(\t\022\017\n\007messag" +
      "e\030\002 \001(\t2\310\001\n\004Chat\0224\n\005login\022\024.protos.Login" +
      "Request\032\025.protos.LoginResponse\022F\n\013sendMe" +
      "ssage\022\032.protos.SendMessageRequest\032\033.prot" +
      "os.SendMessageResponse\022B\n\016receiveMessage" +
      "\022\035.protos.ReceiveMessageRequest\032\017.protos" +
      ".Message0\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protos_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_LoginRequest_descriptor,
        new java.lang.String[] { "UserId", "Password", });
    internal_static_protos_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_LoginResponse_descriptor,
        new java.lang.String[] { "Status", "JwtToken", });
    internal_static_protos_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_SendMessageRequest_descriptor,
        new java.lang.String[] { "RecipientUserId", "Message", "JwtToken", });
    internal_static_protos_SendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_SendMessageResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_protos_ReceiveMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protos_ReceiveMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ReceiveMessageRequest_descriptor,
        new java.lang.String[] { "JwtToken", });
    internal_static_protos_Message_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protos_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Message_descriptor,
        new java.lang.String[] { "From", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
