// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package protos;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string jwtToken = 2;</code>
   */
  java.lang.String getJwtToken();
  /**
   * <code>string jwtToken = 2;</code>
   */
  com.google.protobuf.ByteString
      getJwtTokenBytes();
}
