// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package protos;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
