// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package protos;

public interface ReceiveMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.ReceiveMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jwtToken = 1;</code>
   */
  java.lang.String getJwtToken();
  /**
   * <code>string jwtToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getJwtTokenBytes();
}
